name: Remyx Recommendation
on:
  workflow_dispatch:
jobs:
  recommend:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: write
      pull-requests: write
      issues: write
    env:
      REMYX_API_KEY: ${{ secrets.REMYX_API_KEY }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
    steps:
      - uses: remyxai/remyx-recommendation-action@v1.1.5
        with:
          interest-id: c69e32c3-b4dd-4212-a3be-dda26a25d175
          rate-limit-days: 0
          pin-arxiv: '2605.19972v1'
